# Generated by Django 6.0.4 on 2026-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('duration_minutes', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('congestion_level', models.IntegerField()),
                ('route_type', models.CharField(default='fastest', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_weekend', models.BooleanField()),
                ('is_rush_hour', models.BooleanField()),
                ('weather', models.CharField(choices=[('Clear', 'Clear'), ('Rain', 'Rain'), ('Fog', 'Fog'), ('Snow', 'Snow'), ('Cloudy', 'Cloudy')], max_length=20)),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('road_construction', models.BooleanField()),
                ('accident', models.BooleanField()),
                ('traffic_volume', models.IntegerField()),
                ('predicted_congestion', models.IntegerField(choices=[(0, 'Low Traffic'), (1, 'Medium Traffic'), (2, 'High Traffic'), (3, 'Severe Traffic')])),
                ('predicted_travel_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
