# Generated by Django 6.0.4 on 2026-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficprediction',
            name='accident',
        ),
        migrations.RemoveField(
            model_name='trafficprediction',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='trafficprediction',
            name='road_construction',
        ),
        migrations.RemoveField(
            model_name='trafficprediction',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='trafficprediction',
            name='traffic_volume',
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='destination_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='source_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
