# Generated by Django 6.0.4 on 2026-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0002_remove_trafficprediction_accident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficprediction',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='trafficprediction',
            name='source_location',
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='accident',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='precipitation',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='road_construction',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='temperature',
            field=models.FloatField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficprediction',
            name='traffic_volume',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
