# Generated by Django 6.0.4 on 2026-05-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0004_routehistory_user_trafficprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routehistory',
            name='user',
        ),
    ]
