# Generated by Django 6.0.4 on 2026-05-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0005_remove_routehistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficprediction',
            name='user',
        ),
    ]
